name: Publish nuget package

on:
  workflow_call:
    inputs:
      workingDirectory:
        required: true
        type: string
      repositoryUrl:
        required: true
        type: string
    secrets:
      NUGET_API_KEY:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Run GitVersion
        uses: gittools/actions/gitversion/execute@v0.9.7
      
      - name: Add nuget github source
        run: dotnet nuget add source https://nuget.pkg.github.com/bags-com-ua/index.json -n github -u prostakov -p ${{ secrets.NUGET_API_KEY }} --store-password-in-clear-text

      - name: TEST
        run: echo ${{ github.head_ref }}
        
      - name: Create nuget package
        run: dotnet pack -c Release /p:Version=${GITVERSION_FULLSEMVER/+/.} /p:RepositoryUrl=${{ inputs.repositoryUrl }}
        working-directory: ${{ inputs.workingDirectory }}
        
      - name: Publish nuget package
        run: dotnet nuget push ${{ inputs.workingDirectory }}/**/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source github --no-symbols true
